### ISSUE TITLE
OverflowException when deserializing byte[]

### ISSUE THREAD

**Issue by Titas22** [dbolin/Apex.Serialization#103]
Hi,
I am trying to use Apex serialiser to serialise some objects with data stored in them. Some of that data is stored as byte[] and I noticed that the byte[] data is missing from the deserialised objects. I tried to serialise just byte[] and it seems to be throwing a OverflowException. Is there any way to work around this? 

Many Thanks,
Titas

**Library Version Used & .NET Runtime Version**: 
Apex.Serialization 1.3.4
.NET Framework 4.7.1
Platform Target: x64

**Steps to Reproduce**:
1. Create byte[]
2. Serialise it and save it to file
3. Try to load from file an deserialise

**Expected Behavior**:
It should work

**Actual Behavior**:
It throws OverflowException and fails to reload
```
Exception thrown: 'System.OverflowException' in Apex.Serialization.dll
An unhandled exception of type 'System.OverflowException' occurred in Apex.Serialization.dll
Array dimensions exceeded supported range.
```

Code to reproduce:
```
using Apex.Serialization;
using System;
using System.IO;

namespace ConsoleApp2
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create byte array
            Random rnd = new Random(22);
            byte[] byteData = new byte[10];
            rnd.NextBytes(byteData);

            // Save to file - this seems to work fine
            Save(byteData, @"D:\test1.bin");

            // Load from file - this throws OverflowException
            byte[] b1 = Load<byte[]>(@"D:\test1.bin");

            Console.WriteLine("Success");
            Console.ReadLine();
        }

        public static void Save(object inv, string filepath)
        {
            using (FileStream writeFile = File.Create(filepath))
            {
                using (IBinary apex = Binary.Create())
                {
                    apex.Write(inv, writeFile);
                }
            }
        }
        public static T Load<T>(string filepath)
        {
            T results;
            using (FileStream readFile = File.OpenRead(filepath))
            {
                using (IBinary apex = Binary.Create())
                {
                    results = apex.Read<T>(readFile);
                }
            }
            return results;
        }
    }
}
```

**Comment by dbolin** [comment]
Definitely looks like a bug.  I'll check this.

**Comment by dbolin** [comment]
Well, it turns out this is intended behavior.  Write is called with a parameter type of "object", which means that the serializer will write the type information to the output.  But the Read method is called with the generic type parameter of "byte[]" so the deserializer doesn't look for type information in the input, resulting in a seemingly random error.

Version 2.0+ has a settings flag to verify you're attempting to deserialize data that corresponds to the types being read, so that should catch things like this, but version 2 doesn't support .net framework so that may not be helpful.

In any case, you can fix the problem here by either adding changing Save to Save<T>(T inv...) or doing the opposite to the Load method.

**Comment by Titas22** [comment]
Thanks, that seems to work fine 👍
