### ISSUE TITLE
Question: Is Apex.Serialization thread safe?

### ISSUE THREAD

**Issue by zwanderer** [dbolin/Apex.Serialization#46]
Documentation doesn't mention thread safety but it says to reuse instances: "Always reuse serializer instances when possible, as the instance caches a lot of data to improve performance when repeatedly serializing or deserializing objects."

I have a small test case where two simultaneous tasks running serialization and sharing the same instance, it either write zero bytes or invalid bytes to stream.
[ApexBug.zip](https://github.com/dbolin/Apex.Serialization/files/4033598/ApexBug.zip)

**Comment by dbolin** [comment]
Class instances are not thread safe, static methods should be unless otherwise noted in their documentations.  I'll update the Readme to point that out.

You should reuse serializer instances - if you need to do that across multiple threads you should use an object pool to ensure that only a single thread owns the instance at a time.  I recommend using the Microsoft.Extensions.ObjectPool package as it's really easy to set up.

**Comment by zwanderer** [comment]
Ok, thanks for the response.
