### ISSUE TITLE
Stackoverflow when deserializing large object graph

### ISSUE THREAD

**Issue by Zoxive** [dbolin/Apex.Serialization#99]
**Library Version Used & .NET Runtime Version**: 
Reproduced in 1.3.3 (version we were on at the time) and 2.0.1
.NET 3.0 and 3.1 tested as well

**Steps to Reproduce**:
I'm still attempting to create a reproducible project.. the object we are serializing is quite a large graph so i havent been able to reproduce it in a simpler form yet.

**Expected Behavior**:
Deserialize

**Actual Behavior**:
Dont explode

**Notes**
I'm hopeful that the dynamic code generation can be rewritten to be more stack efficient, this appears to be the problem. (Feels similar to https://github.com/dotnet/aspnetcore/issues/2737 fixed by https://github.com/dotnet/extensions/pull/570)

If i manually set my StackSize to really high it deserializes fine. ``set COMPlus_DefaultStackSize=10000000``

**Comment by dbolin** [comment]
Unfortunately, this is due to the recursive nature of the (de)serialization - easiest reproduction is simply a LinkedList with 10's or 100's of thousands of elements.  I did some experimentation with an iterative approach, but implementation was not trivial and an early prototype indicated it wouldn't perform as well in general.  Definitely something I'd like to look into again, though.

There's not a lot of workarounds I can think of from the consumer side.  You can either make your object graph have a flatter structure, so it's less deep (can be difficult, especially when using immutable data structures), or increase stack size.  If you don't want to set the default stack size (as that would use a lot of memory unnecessarily) you can explicitly create threads dedicated to (de)serialization with a significantly larger stack - you generally shouldn't need more than one per CPU core as this type of processing is CPU bound anyway.

Let me know if you think one of these workarounds will work, at least for a while, or whether you need an alternative serialization mode sooner.

**Comment by Zoxive** [comment]
Yea I thought about a flatter object graph, and i have an idea for something that should help. Trying it out now.

**Comment by Zoxive** [comment]
My flattening experiment worked. So I'll keep moving in that direction and finish working on implementing it fully.

Thanks for the feedback.
